server {
    listen 80;
    server_name api.seset.xyz;
    return 301 https://$host$request_uri;
}

server {
    server_name api.seset.xyz;
    listen 443 ssl;
    http2 on;
    
    # 这里为了兼容你的环境，使用了你在本机的 let's encrypt 证书路径
    ssl_certificate /etc/letsencrypt/live/api.seset.xyz/fullchain.pem; 
    ssl_certificate_key /etc/letsencrypt/live/api.seset.xyz/privkey.pem; 
    
    location / {
        proxy_set_header        X-Real-IP       $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://rustdesk:21114/;
    }

    location /ws/id {
        proxy_pass http://rustdesk:21118;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /ws/relay {
        proxy_pass http://rustdesk:21119;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
